### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by astronouth7303** [curiousdannii/gnusto#21]
If I wanted to use gnusto in my own project, what would I have to do? What are the public APIs?

**Comment by curiousdannii** [comment]
Don't use Gnusto, it's a dead project. Use https://github.com/curiousdannii/ifvms.js. Which is also lacking in documentation, but it's much more straight forward. https://github.com/curiousdannii/ifvms.js/blob/master/dist/bootstrap.js gives the basics needed to use it.
